"use client";

import { Header } from "@/components/Header";
import { DragDropUpload } from "@/components/DragDropUpload";
import { LanguageSelector } from "@/components/LanguageSelector";
import { Studio } from "@/components/Studio";
import { AdBanner, AdInterstitial } from "@/components/Ads";
import { useApp } from "@/lib/store";
import { cn } from "@/lib/utils";

export default function Home() {
  const {
    videoFile,
    hasApiKey,
    status,
    statusMessage,
    error,
    transcription,
    transcribe,
  } = useApp();

  const busy = status === "transcribing" || status === "exporting";
  const canGenerate = Boolean(videoFile && hasApiKey) && !busy;

  return (
    <div className="flex min-h-screen flex-col bg-[var(--background)]">
      <Header />

      <AdInterstitial
        open={status === "transcribing"}
        title="Your captions are being generated by Gemini. Sit tight — here's a quick ad."
      />

      <AdBanner variant="header" />

      <main className="mx-auto w-full max-w-6xl flex-1 space-y-8 px-4 py-8">
        <section className="text-center">
          <h1 className="font-display text-3xl font-semibold tracking-tight text-[var(--foreground)] sm:text-5xl">
            AI Captions
            <span className="text-[var(--brand-blue)]"> 100% Free</span>
          </h1>
          <p className="mx-auto mt-3 max-w-2xl text-[var(--muted-foreground)]">
           Auto-Captions That Don't Suck. 100% Free. Full HD. Unlimited.
          </p>
        </section>

        <section className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]">
          <div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5">
            <DragDropUpload />
          </div>
          <div className="flex flex-col justify-center gap-4 rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5">
            <LanguageSelector />
            <button
              onClick={transcribe}
              disabled={!canGenerate}
              className="w-full rounded-xl bg-[var(--brand-blue)] px-4 py-3 text-sm font-medium text-white transition-opacity hover:opacity-90 disabled:opacity-40"
            >
              {status === "transcribing"
                ? "Transcribing…"
                : "Generate Captions"}
            </button>
            {!hasApiKey ? (
              <p className="text-xs text-[var(--muted-foreground)]">
                Add your Gemini API key (top right) to begin.
              </p>
            ) : null}
            {!videoFile ? (
              <p className="text-xs text-[var(--muted-foreground)]">
                Upload a video to enable generation.
              </p>
            ) : null}
          </div>
        </section>

        {(statusMessage || error) && (
          <div
            className={cn(
              "rounded-xl border px-4 py-3 text-sm",
              error
                ? "border-[var(--destructive-2)]/40 bg-[var(--destructive-2)]/10 text-[var(--destructive-2)]"
                : "border-[var(--border)] bg-[var(--card)] text-[var(--foreground)]",
            )}
          >
            {error ?? statusMessage}
          </div>
        )}

        {transcription ? (
          <section className="space-y-3">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-medium text-[var(--foreground)]">
                Caption Studio
              </h2>
              <span className="rounded-full bg-[var(--editor-card)] px-3 py-1 text-xs text-[var(--editor-text-muted)]">
                {transcription.words.length} words · {transcription.language}
              </span>
            </div>
            <Studio />
          </section>
        ) : null}
      </main>

      <AdBanner variant="footer" />
    </div>
  );
}
