"use client";

import { useEffect, useRef } from "react";
import { Header } from "@/components/Header";
import { DragDropUpload } from "@/components/DragDropUpload";
import { LanguageSelector } from "@/components/LanguageSelector";
import { Studio } from "@/components/Studio";
import { AdBanner, AdInterstitial } from "@/components/Ads";
import { useApp } from "@/lib/store";
import { cn } from "@/lib/utils";
import { motion, type Variants } from "framer-motion";

const container: Variants = {
  hidden: {},
  show: { transition: { staggerChildren: 0.12, delayChildren: 0.05 } },
};

const item: Variants = {
  hidden: { opacity: 0, y: 16 },
  show: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: "easeOut" },
  },
};

export default function Home() {
  const {
    videoFile,
    hasApiKey,
    status,
    statusMessage,
    error,
    progress,
    wordsSoFar,
    transcription,
    transcribe,
  } = useApp();

  const busy = status === "transcribing" || status === "exporting";
  const canGenerate = Boolean(videoFile && hasApiKey) && !busy;

  const studioRef = useRef<HTMLElement | null>(null);
  useEffect(() => {
    if (status === "ready" && studioRef.current) {
      studioRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }, [status]);

  return (
    <div className="flex min-h-screen flex-col bg-[var(--background)]">
      <Header />

      <AdInterstitial
        open={status === "transcribing"}
        title="Your captions are being generated by Gemini. Sit tight — here's a quick ad."
        progress={progress}
        words={wordsSoFar}
      />

      <AdBanner variant="header" />

      <motion.main
        variants={container}
        initial="hidden"
        animate="show"
        className="mx-auto w-full max-w-6xl flex-1 space-y-8 px-4 py-8"
      >
        <motion.section variants={item} className="text-center">
          <h1 className="font-display text-3xl font-semibold tracking-tight text-[var(--foreground)] sm:text-5xl">
            AI Captions
            <span className="text-[var(--brand-blue)]"> 100% Free</span>
          </h1>
          <p className="mx-auto mt-3 max-w-2xl text-[var(--muted-foreground)]">
           Auto-Captions That Don't Suck. 100% Free. Full HD. Unlimited.
          </p>
        </motion.section>

        <motion.section variants={item} className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]">
          <div className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5">
            <DragDropUpload />
          </div>
          <div className="flex flex-col justify-center gap-4 rounded-2xl border border-[var(--border)] bg-[var(--card)] p-5">
            <LanguageSelector />
            <button
              onClick={transcribe}
              disabled={!canGenerate}
              className="w-full rounded-xl bg-[var(--brand-blue)] px-4 py-3 text-sm font-medium text-white transition-opacity hover:opacity-90 disabled:opacity-40"
            >
              {status === "transcribing"
                ? "Transcribing…"
                : "Generate Captions"}
            </button>
            {!hasApiKey ? (
              <p className="text-xs text-[var(--muted-foreground)]">
                Add your Gemini API key (top right) to begin.
              </p>
            ) : null}
            {!videoFile ? (
              <p className="text-xs text-[var(--muted-foreground)]">
                Upload a video to enable generation.
              </p>
            ) : null}
          </div>
        </motion.section>

        {status === "transcribing" ? (
          <motion.section
            variants={item}
            className="rounded-2xl border border-[var(--border)] bg-[var(--card)] p-6"
          >
            <div className="mb-2 flex items-center justify-between">
              <p className="text-sm font-medium text-[var(--foreground)]">
                Generating captions…
              </p>
              <p className="text-sm text-[var(--muted-foreground)]">
                {Math.round(progress * 100)}% · {wordsSoFar} words
              </p>
            </div>
            <div className="h-2.5 w-full overflow-hidden rounded-full bg-[var(--editor-card)]">
              <div
                className="h-full rounded-full bg-[var(--brand-blue)] transition-all duration-300"
                style={{ width: `${Math.round(progress * 100)}%` }}
              />
            </div>
            <p className="mt-3 text-xs text-[var(--muted-foreground)]">
              Transcribing word-by-word with Gemini. Your caption templates and
              player will open automatically when finished.
            </p>
          </motion.section>
        ) : null}

        {(statusMessage || error) && (
          <div
            className={cn(
              "rounded-xl border px-4 py-3 text-sm",
              error
                ? "border-[var(--destructive-2)]/40 bg-[var(--destructive-2)]/10 text-[var(--destructive-2)]"
                : "border-[var(--border)] bg-[var(--card)] text-[var(--foreground)]",
            )}
          >
            {error ?? statusMessage}
          </div>
        )}

        {transcription ? (
          <motion.section
            ref={studioRef}
            variants={item}
            initial="hidden"
            animate="show"
            className="space-y-3"
          >
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-medium text-[var(--foreground)]">
                Caption Studio
              </h2>
              <span className="rounded-full bg-[var(--editor-card)] px-3 py-1 text-xs text-[var(--editor-text-muted)]">
                {transcription.words.length} words · {transcription.language}
              </span>
            </div>
            <Studio />
          </motion.section>
        ) : null}
      </motion.main>

      <AdBanner variant="footer" />
    </div>
  );
}
